name: Generate Snake Animation

on:
  push:
    branches:
    - master
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente para atualizar a animação

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user_name: Yago2023   # Substitua pelo seu nome de usuário
          outputs: dist/snake.svg
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # Define a branch onde a animação será armazenada
          build_dir: dist
